# Generated by Django 6.1.1 on 2026-09-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_academyenrollment_diplomatinquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyenrollment',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academyenrollment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
