# Generated by Django 6.1.1 on 2026-10-02 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_adminactivitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='fulfillment_status',
            field=models.CharField(default='Incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='price',
            field=models.CharField(default='1,000', max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='price_set',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdminStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
