# Generated by Django 6.1.1 on 2026-10-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_contactmessage_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diplomatinquiry',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diplomatinquiry',
            name='fulfillment_status',
            field=models.CharField(default='Incomplete', max_length=50),
        ),
        migrations.AddField(
            model_name='diplomatinquiry',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='diplomatinquiry',
            name='price',
            field=models.CharField(default='1,000', max_length=50),
        ),
        migrations.AddField(
            model_name='diplomatinquiry',
            name='price_set',
            field=models.BooleanField(default=False),
        ),
    ]
